title: Lore Moment Wiki/Database!
description: A (somewhat) updated wiki for Lore Moment!
theme: just-the-docs

logo: "/doyouarehavestupidito.png"
favicon_ico: "/doyouarehavestupidito.ico"

url: https://just-the-docs.github.io

color_scheme: dark

aux_links:
  "Quick Join Link":
    - "https://www.roblox.com/share?code=7eec4a47e032cd419191376b415e51e1&type=Server"

aux_links_new_tab: true

callouts:
  warning:
    title: [ WARNING ]
    color: red
  developing:
    title: NOTICE
    color: yellow
  new:
    title: NEW
    color: green
  updated:
    title: UPDATED
    color: blue
